### PR TITLE
Analytics: Add url to PostHog CLI Event for fern generate --docs

### PR DESCRIPTION
**Pull request by dannysheridan**

### CODE REVIEW

**Review by dsinghvi — CHANGES_REQUESTED** [review]
@dannysheridan i can own these changes

**Comment by dsinghvi** [comment]
> I am unable to run `yarn test` locally. Could have to do with my local setup.
> 
> $ fern % yarn test -u Type Error: Cannot read properties of undefined (reading '/Users/dannysheridan/Documents/Coding/fern/.pnp.cjs')

would recommend downgrading your node version to 18

**Comment by dsinghvi** [comment]
Closing out since this can be done from the fern cloud backend!

**Comment by dianetc** [comment]
@dsinghvi I had the same type error as @dannysheridan. 
Your fix of downgrading to version 18 resolved it, but maybe this trick should be noted somewhere obvious?
I wouldn't have caught it, without searching through ferns issues/PRs

**Pull request closed without merging**
