### PR TITLE
fix: set `Binds` in `HostConfig` when running containers

### PR DESCRIPTION
**Pull request by mstade**
The Docker Engine API docs states the `Binds` option should be nested under `HostConfig`: https://docs.docker.com/engine/api/v1.46/#tag/Container/operation/ContainerCreate

This seems to fix an issue some of us are seeing with an unhelpful error about `/fern/config.json` not existing. More context available here: https://github.com/fern-api/fern/issues/1998#issuecomment-2295408719

### CODE REVIEW

**Comment by dsinghvi** [comment]
@mstade really appreciate you fixing this!

**Review by dsinghvi — APPROVED** [review]

**Comment by mstade** [comment]
@dsinghvi no worries, glad to help! What's your release process like? When can I expect this to make its way to npm?

**Comment by dannysheridan** [comment]
@mstade echoing Deep's sentiment, thanks for your help here! 

We tend to cut releases multiple times per week. My hunch is this will be available in NPM tomorrow! You can stay tuned here https://github.com/fern-api/fern/releases

**Comment by mstade** [comment]
Perfect, thanks @dannysheridan!

**Pull request merged**
