### PR TITLE
(fix, docs): adapt all the middle content we have on the docs product

### PR DESCRIPTION
**Pull request by dsinghvi**
We don't really cover much in the docs about Ferns docs product. This PR attempts to change that. The updated information architecture looks like this:

Screenshot 2024-05-03 at 3 48 26 PM

### CODE REVIEW

**Comment by dannysheridan** [comment]
Getting Started
- Quickstart
- Project Structure (docs.yml, fern folder, fern.config.json, GitHub as CMS)
- Showcase

Building your Docs
- Styling
-- Colors
-- Fonts 
-- Light/Dark Mode
-- Built-in Components
-- Custom Components
-- Custom CSS
- Writing Content
-- Using Markdown
-- Using MDX/JSX
-- Frontmatter
-- Reusable Snippets
- Previewing
-- Local Preview
-- PR Previews
- API Reference
-- Using OpenAPI
-- Using Fern Definition
-- Using MDX
-- API Playground
-- API Key Injection
- Versioning

Shipping Your Docs
- Custom Domain
- Collect Analytics
- Search by Algolia
- AI Chatbot

Protecting Your Docs
- Password-protected
- SSO
- JWT (?)

Comparing
- Fern to Mintlify
- Fern to ReadMe

**Comment by dannysheridan** [comment]
Opinion: the showcase cards should tell a user *what* to look for. (e.g., Primer -> Versioning)

**Comment by abvthecity** [comment]
Getting Started
- Quickstart
- Project Structure (docs.yml, fern folder, fern.config.json, GitHub as CMS)
- Showcase

Building your Docs
- Navigation
  - Sections
  - Tabs
  - Versions
  - API Reference
  - Search
- Customization
  - Theme (includes colors, light/dark mode)
  - Fonts
  - Layout (widths, heights, placement)
  - [pro] Custom CSS
  - [pro] Custom JS
- Writing Content
  - Using Markdown
  - Using MDX/JSX
  - Frontmatter
  - Reusable Snippets
  - Versioning
- Previewing
  - Local Preview
  - PR Previews
- API Reference
  - Using OpenAPI
  - Using Fern Definition
  - Using MDX
  - API Playground
  - API Key Injection
- Custom Domain
  - Custom Subdomain
  - Custom Subpath

Features
- Search by Algolia
- AI Chatbot
- Protect Your Docs
  - Password-protected
  - SSO
- Connecting Analytics

Components
- Built-in Components
- Custom Components

Comparing
- Fern to Mintlify
- Fern to ReadMe

**Comment by dannysheridan** [comment]
turning this into docs.yml:

```
  - tab: docs
    layout:
      - section: Getting Started
        contents:
          - page: Quickstart
            path: ./pages/docs/getting-started/quickstart.mdx
          - page: Project Structure
            path: ./pages/docs/getting-started/project-structure.mdx
          - page: Showcase
            path: ./pages/docs/getting-started/showcase.mdx
      - section: Building your Docs
        contents:
          - section: Navigation
            contents:
              - page: Sections
                path: ./pages/docs/building-your-docs/navigation/sections.mdx
              - page: Tabs
                path: ./pages/docs/building-your-docs/navigation/tabs.mdx
              - page: Versions
                path: ./pages/docs/building-your-docs/navigation/versions.mdx
              - page: API Reference
                path: ./pages/docs/building-your-docs/navigation/api-reference.mdx
              - page: Search
                path: ./pages/docs/building-your-docs/navigation/search.mdx
          - section: Customization
            contents:
              - page: Theme
                path: ./pages/docs/building-your-docs/customization/theme.mdx
              - page: Fonts
                path: ./pages/docs/building-your-docs/customization/fonts.mdx
              - page: Layout
                path: ./pages/docs/building-your-docs/customization/layout.mdx
              - page: Header & Footer [pro]
                path: ./pages/docs/building-your-docs/customization/header-footer.mdx
              - page: Custom CSS [pro]
                path: ./pages/docs/building-your-docs/customization/custom-css.mdx
              - page: Custom JS [pro]
                path: ./pages/docs/building-your-docs/customization/custom-js.mdx
          - section: Writing Content
            contents:
              - page: Using Markdown
                path: ./pages/docs/building-your-docs/writing-content/markdown.mdx
              - page: Using MDX/JSX
                path: ./pages/docs/building-your-docs/writing-content/mdx-jsx.mdx
              - page: Frontmatter
                path: ./pages/docs/building-your-docs/writing-content/frontmatter.mdx
              - page: Reusable Snippets
                path: ./pages/docs/building-your-docs/writing-content/reusable-snippets.mdx
              - page: Versioning
                path: ./pages/docs/building-your-docs/writing-content/versioning.mdx
          - section: Previewing
            contents:
              - page: Local Preview
                path: ./pages/docs/building-your-docs/previewing/local-preview.mdx
              - page: PR Previews
                path: ./pages/docs/building-your-docs/previewing/pr-previews.mdx
          - section: API Reference
            contents:
              - page: Using OpenAPI
                path: ./pages/docs/building-your-docs/api-reference/openapi.mdx
              - page: Using Fern Definition
                path: ./pages/docs/building-your-docs/api-reference/fern-definition.mdx
              - page: Using MDX
                path: ./pages/docs/building-your-docs/api-reference/using-mdx.mdx
              - page: API Playground
                path: ./pages/docs/building-your-docs/api-reference/api-playground.mdx
              - page: API Key Injection
                path: ./pages/docs/building-your-docs/api-reference/api-key-injection.mdx
          - section: Custom Domain
            contents:
              - page: Custom Subdomain
                path: ./pages/docs/building-your-docs/custom-domain/custom-subdomain.mdx
              - page: Custom Subpath
                path: ./pages/docs/building-your-docs/custom-domain/custom-subpath.mdx
      - section: Features
        contents:
          - page: Search by Algolia
            path: ./pages/docs/features/search-algolia.mdx
          - page: AI Chatbot
            path: ./pages/docs/features/ai-chatbot.mdx
          - section: Protect Your Docs
            contents:
              - page: Password-protected
                path: ./pages/docs/features/protect-your-docs/password-protected.mdx
              - page: SSO
                path: ./pages/docs/features/protect-your-docs/sso.mdx
          - page: Connecting Analytics
            path: ./pages/docs/features/connecting-analytics.mdx
      - section: Components
        contents:
          - page: Built-in Components
            path: ./pages/docs/components/built-in.mdx
          - page: Custom Components
            path: ./pages/docs/components/custom.mdx
      - section: Comparing
        contents:
          - page: Fern to Mintlify
            path: ./pages/docs/comparing/fern-to-mintlify.mdx
          - page: Fern to ReadMe
            path: ./pages/docs/comparing/fern-to-readme.mdx
```

**Comment by dannysheridan** [comment]
Getting Started
- Quickstart
- Project Structure (docs.yml, fern folder, fern.config.json, GitHub as CMS)
- Showcase

Building your Docs
- Navigation
  - Sections
  - Tabs
  - Versions
  - API Reference
  - Search
- Customization
  - Theme (includes colors, light/dark mode)
  - Fonts
  - Layout (widths, heights, placement)
  - [pro] Header & Footer
  - [pro] Custom CSS
  - [pro] Custom JS
- Writing Content
  - Using Markdown
  - Using MDX/JSX
  - Frontmatter
  - Reusable Snippets
  - Versioning
- Previewing
  - Local Preview
  - PR Previews
- API Reference
  - Using OpenAPI
  - Using Fern Definition
  - Using MDX
  - API Playground
  - API Key Injection
- Custom Domain
  - Custom Subdomain
  - Custom Subpath

Features
- Search by Algolia
- AI Chatbot
- Protect Your Docs
  - Password-protected
  - SSO
- Analytics 
  - Google Analytics
  - Segment
  - Mixpanel 
  - PostHog
- Integrations
  - GitHub
  - Intercom
  - HubSpot
  - Slack
- SEO

Components
- Built-in Components
- Custom Components

Comparing
- Fern vs Mintlify
- Fern vs ReadMe

**Pull request closed without merging**
