### PR TITLE
docs: add doc on generating openapi spec for express backend

### PR DESCRIPTION
**Pull request by AlgoDame**
Added documentation on how to generate an OpenAPI spec for an Express backend.

### CODE REVIEW

**Comment by zachkirsch** [comment]
Thanks @AlgoDame! Looks awesome.

Maybe makes more sense to have a `guides/` directory in the root of this repo. Can you make that folder and move this markdown file into that folder?

Thanks!

**Comment by AlgoDame** [comment]
Sure. I'll do that.

**Comment by aevitas** [comment]
Looks great! This would also be very useful in the docs repo once we start serving the new documentation from it!

**Comment by AlgoDame** [comment]
@zachkirsch, I have created a guides folder in the root of the project and moved the express guide to the guides folder.

**Comment by zachkirsch** [comment]
Thanks so much!

**Pull request merged**
