### PR TITLE
Improvement: upgrade generateInvocations

### PR DESCRIPTION
**Pull request by dannysheridan**
Added `yarn open`

### CODE REVIEW

**Comment by dsinghvi** [comment]
what does yarn open do?

**Comment by dannysheridan** [comment]
Error when running yarn test:ete -u AND yarn test -u

```
$ yarn test -u
../cli/login/src/auth0-login/doAuth0DeviceAuthorizationFlow.ts:5:18 - error TS2307: 
Cannot find module 'open' or its corresponding type declarations.
```

ChatGPT:

> It looks like you're encountering TypeScript errors related to missing module declarations for 'open'. This issue usually occurs when the required module is not installed in your project or its type declarations are missing. Here are some steps you can follow to resolve this issue:
> 
> Install the 'open' module: If you haven't installed the 'open' module yet, you can do so by running yarn add open in your project's root directory. This will install the module and add it to your project's dependencies.

**Comment by dannysheridan** [comment]
> yarn add open

Opens stuff like URLs, files, executables. https://yarnpkg.com/package?name=open

**Comment by dsinghvi** [comment]
Screenshot 2024-01-28 at 4 20 51 PM

did you try running `yarn install` before running `yarn test -u` ?

**Comment by dsinghvi** [comment]
ill get this over the line today

**Comment by dannysheridan** [comment]
closing in favor of https://github.com/fern-api/fern/pull/2830

**Pull request closed without merging**
