### PR TITLE
(fix): updating sdk invocation versions

### PR DESCRIPTION
**Pull request by bsinghvi**
Used the generator versions here - https://github.com/fern-api/fern?tab=readme-ov-file + the changelog to decide on the default version.

### CODE REVIEW

**Comment by dsinghvi** [comment]
@bsinghvi you'll need to fix ete tests here `yarn workspace @fern-api/ete-tests test -u` and then we are g2g

**Comment by dannysheridan** [comment]
is there a way to make this dynamic (inspired by what Armando did here: https://github.com/fern-api/fern/blob/8633c289e09088ad865303c8b74005dea260dda9/README.md?plain=1#L79)

**Comment by bsinghvi** [comment]
@dannysheridan there would still have to be some level of manual intervention to determine which version we should mark as safe to be the default invocation version. right now, Armando's just grabs the latest, which could potentially not be release safe

**Comment by dsinghvi** [comment]
> is there a way to make this dynamic? I'm inspired by what Armando did here:
> 
> https://github.com/fern-api/fern/blob/8633c289e09088ad865303c8b74005dea260dda9/README.md?plain=1#L79
> 
> )



> @dannysheridan there would still have to be some level of manual intervention to determine which version we should mark as safe to be the default invocation version. right now, Armando's just grabs the latest, which could potentially not be release safe

That's right -- in fact the latest TS release has some issues so have to wait to merge this

**Comment by bsinghvi** [comment]
@dsinghvi this PR doesn't update it to the latest for the TypeScript SDK - are there concerns with 12.9?

**Comment by dannysheridan** [comment]
image
getting an error when I try to run: `yarn workspace @fern-api/ete-tests test -u`

@dsinghvi can you land this PR?

**Pull request closed without merging**
