### PR TITLE
Docs remove redirect links

### PR DESCRIPTION
**Pull request by atwooddc**

### CODE REVIEW

**Comment by atwooddc** [comment]
preview: https://fern-beta-preview-5b287bf0-3af5-45cb-8958-9549657d0bdb.docs.buildwithfern.com

**Review by dannysheridan — COMMENTED** [review]
@atwooddc why the slug changes in `docs.yml`? Would approve the PR to the other 4 files edited as-is.

**Comment by atwooddc** [comment]
> @atwooddc why the slug changes in `docs.yml`? Would approve the PR to the other 4 files edited as-is.

SEO penalizes temporary redirects, which is what those links returned. If we could make the old nav bar links return a 308 response (permanent redirect) instead of a 307, that would also be a solution.

**Comment by dannysheridan** [comment]
when I go to the preview link, I see the URL for the docs tab as: `/docs/getting-started/quickstart/getting-started/quickstart`

**Comment by atwooddc** [comment]
corrected tabs slugs

preview: https://fern-beta-preview-1153cd60-2325-4c50-8b47-50f3aa73bf1a.docs.buildwithfern.com

**Review by dannysheridan — APPROVED** [review]

**Pull request merged**
